CREATE TABLE IF NOT EXISTS starlight_analytics_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id VARCHAR(80) NOT NULL,
  event_name VARCHAR(64) NOT NULL,
  anonymous_user_id VARCHAR(100) NOT NULL,
  session_id VARCHAR(100) NOT NULL,
  platform VARCHAR(16) NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  screen_id VARCHAR(64) NULL,
  overlay_id VARCHAR(64) NULL,
  stage_id TINYINT UNSIGNED NULL,
  puzzle_id VARCHAR(100) NULL,
  locale VARCHAR(16) NULL,
  source VARCHAR(100) NULL,
  medium VARCHAR(100) NULL,
  campaign VARCHAR(160) NULL,
  content VARCHAR(160) NULL,
  term VARCHAR(160) NULL,
  elapsed_screen_time DECIMAL(12,3) NULL,
  elapsed_play_time DECIMAL(12,3) NULL,
  remaining_cells SMALLINT UNSIGNED NULL,
  mistake_count SMALLINT UNSIGNED NULL,
  hint_count SMALLINT UNSIGNED NULL,
  target_id VARCHAR(100) NULL,
  target_type VARCHAR(64) NULL,
  is_interactive BOOLEAN NULL,
  x_ratio DECIMAL(8,7) NULL,
  y_ratio DECIMAL(8,7) NULL,
  viewport_width SMALLINT UNSIGNED NULL,
  viewport_height SMALLINT UNSIGNED NULL,
  properties_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_starlight_analytics_event_id (event_id),
  KEY idx_starlight_analytics_time (occurred_at),
  KEY idx_starlight_analytics_session_time (session_id, occurred_at),
  KEY idx_starlight_analytics_filters (platform, locale, source, campaign, stage_id),
  KEY idx_starlight_analytics_heatmap (screen_id, overlay_id, stage_id, occurred_at),
  CONSTRAINT chk_starlight_analytics_stage CHECK (stage_id IS NULL OR stage_id BETWEEN 1 AND 5),
  CONSTRAINT chk_starlight_analytics_x CHECK (x_ratio IS NULL OR x_ratio BETWEEN 0 AND 1),
  CONSTRAINT chk_starlight_analytics_y CHECK (y_ratio IS NULL OR y_ratio BETWEEN 0 AND 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
